spring:
  datasource:
    url: jdbc:postgresql://localhost:6000/kyc_database
    username: kyc_user
    password: kyc_pass
    driverClassName: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false
    database-platform: org.hibernate.dialect.PostgreSQL9Dialect

kyc:
  batch:
    offices:
      backup-executive-office:
        path: "/home/batch/offices/backup/executive-offices.csv"
        fields: idExecutive,idBranch
      offices-load:
        path: "/home/batch/offices/KYC_OFFICES.csv"
        fields: ID_BRANCH,NAME,STREET,NEIGHBORHOOD,CITY,STATE,POSTAL_CODE,BUSINESS_HOURS,LATITUDE,LONGITUDE

logging:
  level:
    root: INFO
    com.kyc: INFO
    org.springframework: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
    org.springframework.batch.item.data: DEBUG